# Site settings
title: Pol Perez Portfolio
description: A portfolio web page.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pol Pérez Granero
user_description: I am a dedicated video games programmer, looking for a place in
  which I'm able to combine my love for mathematics, my imagination
  and my programming skills. Being a regular player of board games
  and TTRPG, I am also interested in game design..
user_title: Video games programmer 
email: polpegra@gmail.com
github_username:  Mefiso
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
